DM Partie 2 : Apprentissage Artificiel
=======

21605783 - Alexis Mortelier - M1 DOP

In [2]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.metrics import *
from sklearn.model_selection import GridSearchCV
from matplotlib import pyplot as plt
from matplotlib.colors import ListedColormap
import matplotlib.patches as mpatches
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression

1 - Question 1
-----

 En utilisant les librairies vues en TP, faites tourner sur ces donnees les algorithmes 1)  kppv  2)  SVM  3)  regression  logistique  et  4)  reseaux  de  neurones  (MLPClassi-fier). Utilisez une technique de validation croisee pour evaluer les performances des classifieurs  et  trouver  les  meilleurs  parametres  pour  resoudre  ce  probleme.  Vous
pouvez utiliser plusieurs criteres d’evaluation comme par exemple le pourcentaged’exemples bien classes, la precision moyenne ou l’aire sous la courbe ROC.

On lis les données

In [3]:
X = pd.read_csv('X.csv', header=None, sep=" ")
y = np.array(pd.read_csv('y.csv', header=None, sep=" "))
y.reshape(y.shape[0],)
X_test = pd.read_csv('X_test.csv', header=None, sep=" ")

In [4]:
print(X.shape)
X.head()


(500, 30)


0         1         2         3         4         5         6   \
0  1.097064 -2.073335  1.269934  0.984375  1.568466  3.283515  2.652874   
1  1.829821 -0.353632  1.685955  1.908708 -0.826962 -0.487072 -0.023846   
2  1.579888  0.456187  1.566503  1.558884  0.942210  1.052926  1.363478   
3 -0.768909  0.253732 -0.592687 -0.764464  3.283553  3.402909  1.915897   
4  1.750297 -1.151816  1.776573  1.826229  0.280372  0.539340  1.371011   

         7         8         9   ...        20        21        22        23  \
0  2.532475  2.217515  2.255747  ...  1.886690 -1.359293  2.303601  2.001237   
1  0.548144  0.001392 -0.868652  ...  1.805927 -0.369203  1.535126  1.890489   
2  2.037231  0.939685 -0.398008  ...  1.511870 -0.023974  1.347475  1.456285   
3  1.451707  2.867383  4.910919  ... -0.281464  0.133984 -0.249939 -0.550021   
4  1.428493 -0.009560 -0.562450  ...  1.298575 -1.466770  1.338539  1.220724   

         24        25        26        27        28        29  
0  1.307686  2.616665  2.109526  2.296076  2.750622  1.937015  
1 -0.375612 -0.430444 -0.146749  1.087084 -0.243890  0.281190  
2  0.527407  1.082932  0.854974  1.955000  1.152255  0.201391  
3  3.394275  3.893397  1.989588  2.175786  6.046041  4.935010  
4  0.220556 -0.313395  0.613179  0.729259 -0.868353 -0.397100  

[5 rows x 30 columns]

In [5]:
print(y.shape)
y

(500, 1)


array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],

KNN
---

In [6]:
tuned_parameters = {
    "n_neighbors": [3,5,11,19],
    "weights": ["uniform", "distance"],
    "metric": ["euclidean", "manhattan"]
}

clf_grid_knn = GridSearchCV(KNeighborsClassifier(),
                        tuned_parameters,
                        verbose = 1,
                        cv = 5,
                        n_jobs = -1
                       )
clf_grid_knn.fit(X, y)

print('\033[34mMeilleur jeu de paramètre trouvé parmi les paramètres proposés:\033[0m')
print(clf_grid_knn.best_estimator_,'\n')
print("\033[34mGrille des scores par combinaison de paramètres testés:\033[0m")
    
elements = clf_grid_knn.cv_results_
for i in np.argsort(elements['mean_test_score']):
    print("%0.3f (+/-%0.03f) for %r"% (elements['mean_test_score'][i],
                                       elements['std_test_score'][i],
                                       elements['params'][i]))

Fitting 5 folds for each of 16 candidates, totalling 80 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.


Meilleur jeu de paramètre trouvé parmi les paramètres proposés:
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform') 

Grille des scores par combinaison de paramètres testés:
0.948 (+/-0.021) for {'metric': 'manhattan', 'n_neighbors': 19, 'weights': 'uniform'}
0.952 (+/-0.015) for {'metric': 'manhattan', 'n_neighbors': 19, 'weights': 'distance'}
0.954 (+/-0.012) for {'metric': 'euclidean', 'n_neighbors': 19, 'weights': 'uniform'}
0.956 (+/-0.010) for {'metric': 'euclidean', 'n_neighbors': 19, 'weights': 'distance'}
0.958 (+/-0.017) for {'metric': 'manhattan', 'n_neighbors': 11, 'weights': 'uniform'}
0.958 (+/-0.017) for {'metric': 'manhattan', 'n_neighbors': 11, 'weights': 'distance'}
0.964 (+/-0.010) for {'metric': 'euclidean', 'n_neighbors': 11, 'weights': 'uniform'}
0.964 (+/-0.010) for {'metric': 'euclidean', 'n_neighbors': 11, 'weights': 'distance'}

[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    2.0s
[Parallel(n_jobs=-1)]: Done  80 out of  80 | elapsed:    2.1s finished
c:\python\python3.7\lib\site-packages\sklearn\model_selection\_search.py:739: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


SVM
---

In [7]:
tuned_parameters = [{'kernel': ['rbf'],
                     'gamma': [1e-1, 1e-2, 1e-3, 1e-4],
                     'C': [1e-2,1e-1,1, 10, 100, 1000]},
                    {'kernel': ['linear'],
                     'C': [1e-2,1e-1,1, 10, 100, 1000]}]

clf_grid_svm = GridSearchCV(svm.SVC(probability=True), 
                        tuned_parameters,
                        cv=5,
                        n_jobs = -1,
                        scoring='accuracy'
                       )
clf_grid_svm.fit(X, y)

print('\033[34mMeilleur jeu de paramètre trouvé parmi les paramètres proposés:\033[0m')
print(clf_grid_svm.best_estimator_,'\n')
print("\033[34mGrille des scores par combinaison de paramètres testés:\033[0m")
    
elements = clf_grid_svm.cv_results_
for i in np.argsort(elements['mean_test_score']):
    print("%0.3f (+/-%0.03f) for %r"% (elements['mean_test_score'][i],
                                       elements['std_test_score'][i],
                                       elements['params'][i]))

Meilleur jeu de paramètre trouvé parmi les paramètres proposés:
SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
    max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False) 

Grille des scores par combinaison de paramètres testés:
0.610 (+/-0.000) for {'C': 0.01, 'gamma': 0.1, 'kernel': 'rbf'}
0.610 (+/-0.000) for {'C': 0.01, 'gamma': 0.01, 'kernel': 'rbf'}
0.610 (+/-0.000) for {'C': 0.01, 'gamma': 0.001, 'kernel': 'rbf'}
0.610 (+/-0.000) for {'C': 0.01, 'gamma': 0.0001, 'kernel': 'rbf'}
0.610 (+/-0.000) for {'C': 0.1, 'gamma': 0.0001, 'kernel': 'rbf'}
0.772 (+/-0.034) for {'C': 0.1, 'gamma': 0.001, 'kernel': 'rbf'}
0.772 (+/-0.038) for {'C': 1, 'gamma': 0.0001, 'kernel': 'rbf'}
0.930 (+/-0.024) for {'C': 0.1, 'gamma': 0.1, 'kernel': 'rbf'}
0.946 (+/-0.022) for {'C': 0.1, 'gamma': 0.01, 'kernel': 'rbf'}
0.946 (+/-0.021) for {'C': 1000, 'gamma': 0.1, 'k

c:\python\python3.7\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Regression logistique
---

In [8]:
tuned_parameters = {
    "C":np.logspace(-3,3,7),
    "penalty":["l1","l2"]
}
clf_grid_logi = GridSearchCV(LogisticRegression(),
                        tuned_parameters,
                        cv = 5,
                        n_jobs = -1,
                       )
clf_grid_logi.fit(X, y)

print('\033[34mMeilleur jeu de paramètre trouvé parmi les paramètres proposés:\033[0m')
print(clf_grid_logi.best_estimator_,'\n')
print("\033[34mGrille des scores par combinaison de paramètres testés:\033[0m")
    
elements = clf_grid_logi.cv_results_
for i in np.argsort(elements['mean_test_score']):
    print("%0.3f (+/-%0.03f) for %r"% (elements['mean_test_score'][i],
                                       elements['std_test_score'][i],
                                       elements['params'][i]))

Meilleur jeu de paramètre trouvé parmi les paramètres proposés:
LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False) 

Grille des scores par combinaison de paramètres testés:
0.894 (+/-0.041) for {'C': 0.001, 'penalty': 'l2'}
0.946 (+/-0.017) for {'C': 1000.0, 'penalty': 'l2'}
0.948 (+/-0.017) for {'C': 0.01, 'penalty': 'l2'}
0.952 (+/-0.015) for {'C': 100.0, 'penalty': 'l2'}
0.972 (+/-0.010) for {'C': 10.0, 'penalty': 'l2'}
0.980 (+/-0.014) for {'C': 0.1, 'penalty': 'l2'}
0.980 (+/-0.013) for {'C': 1.0, 'penalty': 'l2'}
nan (+/-nan) for {'C': 0.001, 'penalty': 'l1'}
nan (+/-nan) for {'C': 0.01, 'penalty': 'l1'}
nan (+/-nan) for {'C': 0.1, 'penalty': 'l1'}
nan (+/-nan) for {'C': 1.0, 'penalty': 'l1'}
nan (+/-nan) for 

c:\python\python3.7\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLP Classifier
---

In [9]:
tuned_parameters = {
    'hidden_layer_sizes': [(50,50,50), (50,100,50), (100,)],
    'activation': ['tanh', 'relu'],
    'solver': ['sgd', 'adam'],
    'alpha': [0.0001, 0.05],
    'learning_rate': ['constant','adaptive'],
}
clf_grid_mlp = GridSearchCV(MLPClassifier(),
                        tuned_parameters,
                        cv = 5,
                        n_jobs = -1,
                       )
clf_grid_mlp.fit(X, y)

print('\033[34mMeilleur jeu de paramètre trouvé parmi les paramètres proposés:\033[0m')
print(clf_grid_mlp.best_estimator_,'\n')
print("\033[34mGrille des scores par combinaison de paramètres testés:\033[0m")
    
elements = clf_grid_mlp.cv_results_
for i in np.argsort(elements['mean_test_score']):
    print("%0.3f (+/-%0.03f) for %r"% (elements['mean_test_score'][i],
                                       elements['std_test_score'][i],
                                       elements['params'][i]))

c:\python\python3.7\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Meilleur jeu de paramètre trouvé parmi les paramètres proposés:
MLPClassifier(activation='tanh', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(50, 100, 50), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='sgd',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False) 

Grille des scores par combinaison de paramètres testés:
0.952 (+/-0.020) for {'activation': 'relu', 'alpha': 0.0001, 'hidden_layer_sizes': (50, 50, 50), 'learning_rate': 'constant', 'solver': 'sgd'}
0.956 (+/-0.016) for {'activation': 'relu', 'alpha': 0.05, 'hidden_layer_sizes': (50, 100, 50), 'learning_rate': 'constant', 'solver': 'sgd'}
0.958 (+/-0.012) for {'activation': 'relu', 'alpha': 0.0001, 

c:\python\python3.7\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Best classifier
---

1.1 - Accuracy
---

In [10]:
y_pred_knn = clf_grid_knn.best_estimator_.predict(X)

y_pred_svm = clf_grid_svm.best_estimator_.predict(X)

y_pred_logi = clf_grid_logi.best_estimator_.predict(X)

y_pred_mlp = clf_grid_mlp.best_estimator_.predict(X)


acc_knn = accuracy_score(y, y_pred_knn)
print("Accuracy d un classifieur KNN:", acc_knn)

acc_svm = accuracy_score(y, y_pred_svm)
print("Accuracy d un classifieur SVM:", acc_svm)

acc_logi = accuracy_score(y, y_pred_logi)
print("Accuracy d un classifieur Logistic Regression:", acc_logi)

acc_mlp = accuracy_score(y, y_pred_mlp)
print("Accuracy d un classifieur MLP:", acc_mlp)

Accuracy d un classifieur KNN: 0.978
Accuracy d un classifieur SVM: 0.988
Accuracy d un classifieur Logistic Regression: 0.986
Accuracy d un classifieur MLP: 0.982


1.2 - Matrice de confusion
---

In [11]:
print("matrice de confusion KNN : \n")
print(confusion_matrix(y, y_pred_knn))
print("\n matrice de confusion SVM : \n")
print(confusion_matrix(y, y_pred_svm))
print("\n matrice de confusion Regression Logistique : \n")
print(confusion_matrix(y, y_pred_logi))
print("\n matrice de confusion MLP : \n")
print(confusion_matrix(y, y_pred_mlp))

matrice de confusion KNN : 

[[304   1]
 [ 10 185]]

 matrice de confusion SVM : 

[[305   0]
 [  6 189]]

 matrice de confusion Regression Logistique : 

[[304   1]
 [  6 189]]

 matrice de confusion MLP : 

[[302   3]
 [  6 189]]


1.3 - Courbe ROC
---

In [12]:
roc_auc = roc_auc_score(y, y_pred_knn)
average_pre = average_precision_score(y, y_pred_knn)
print("Aire sous la courbe ROC d un classifieur KNN:", roc_auc)
print("Aire sous la courbe Rappel/Précission d un KNN:", average_pre," \n")

roc_auc = roc_auc_score(y, y_pred_svm)
average_pre = average_precision_score(y, y_pred_svm)
print("Aire sous la courbe ROC d un classifieur SVM:", roc_auc)
print("Aire sous la courbe Rappel/Précission d un SVM:", average_pre," \n")

roc_auc = roc_auc_score(y, y_pred_logi)
average_pre = average_precision_score(y, y_pred_logi)
print("Aire sous la courbe ROC d un classifieur Regression Logistique:", roc_auc)
print("Aire sous la courbe Rappel/Précission d un Regression Logistique:", average_pre," \n")

roc_auc = roc_auc_score(y, y_pred_mlp)
average_pre = average_precision_score(y, y_pred_mlp)
print("Aire sous la courbe ROC d un classifieur MLP:", roc_auc)
print("Aire sous la courbe Rappel/Précission d un MLP:", average_pre," \n")

Aire sous la courbe ROC d un classifieur KNN: 0.9727196300966793
Aire sous la courbe Rappel/Précission d un KNN: 0.9636173145850565  

Aire sous la courbe ROC d un classifieur SVM: 0.9846153846153847
Aire sous la courbe Rappel/Précission d un SVM: 0.9812307692307692  

Aire sous la courbe ROC d un classifieur Regression Logistique: 0.9829760403530896
Aire sous la courbe Rappel/Précission d un Regression Logistique: 0.9761295546558705  

Aire sous la courbe ROC d un classifieur MLP: 0.9796973518284995
Aire sous la courbe Rappel/Précission d un MLP: 0.9660865384615385  



Un systeme de vote !
---

In [15]:
y_pred=np.mean([y_pred_svm,y_pred_logi,y_pred_mlp], axis=0)
y_pred=[int(x) for x in y_pred] 


500

2 - Question 2
-----

Analysez les resultats obtenus par les classifieursd’un point de vue quantitatif, c’est-a-dire  selon  selon  les  valeurs  de  criteres  d’evaluation  de  performance: comment ́evoluent les r ́esultats en fonction des valeurs des parametres comme par exemplele choix du noyau pour les SVM, les parametres des reseaux de neurones. . .

3 - Question 3
-----

Une  fois  que  vous  avez  trouve  le  meilleur  classifieur,  entraˆınez  le  sur  toutes  lesdonnees a votre disposition et pr ́edisez les classes associ ́ees aux patientes du fichierXtest.csv

In [23]:
y_test0 = clf_grid_svm.best_estimator_.predict(X_test)
y_test1 = clf_grid_logi.best_estimator_.predict(X_test)
y_test2 = clf_grid_mlp.best_estimator_.predict(X_test)
y_test = np.mean([y_test0,y_test1,y_test2], axis=0)
y_test = [int(x) for x in y_test]
y_test
#np.savetxt('y_test.csv', y_test, delimiter=' ')